# Generated by ``run.sh`` from add-on options on every start.
# Edit the add-on configuration in Home Assistant; do not hand-
# edit this file (it is overwritten).

[server]
mode      = "ha"
log_level = "{{ .log_level }}"
data_dir  = "/data"

[webrtc]
turn_url    = "{{ .turn_url }}"
turn_secret = "{{ .turn_secret }}"

[ai]
calendar_import_agent = "{{ .ai_calendar_import_agent }}"

[gfs]
enable   = {{ .gfs_enable }}
base_url = "{{ .gfs_base_url }}"
